# Generated by Django 4.1.3 on 2022-11-18 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_files_title_remove_files_upload_files_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='birthday',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='files',
            name='up_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 18, 20, 54, 59, 948783)),
        ),
    ]
