# Generated by Django 4.1.3 on 2022-11-23 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_addressbook_birthday_alter_files_up_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="up_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 14, 27, 33, 154512)
            ),
        ),
    ]
