# Generated by Django 4.1.3 on 2022-11-23 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_files_up_time_phones_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressbook",
            name="address",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="birthday",
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="addressbook",
            name="phone",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="files",
            name="up_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 16, 33, 46, 898575)
            ),
        ),
    ]
