# Generated by Django 4.1.3 on 2022-11-23 15:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "project",
            "0006_alter_addressbook_address_alter_addressbook_birthday_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="emails",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phones",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="files",
            name="up_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 17, 38, 54, 17432)
            ),
        ),
    ]
